# docker-compose.yml
# For development environment

services:
  db:
    image: postgres:17-trixie
    container_name: django-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_dev:/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: django-rabbitmq
    hostname: "rabbitmq"
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI

  s3:
    image: bitnami/minio:2025.4.22 ### !minio removed console ui in newer version; keep this version for DEV ###
    container_name: minio
    restart: unless-stopped
    volumes:
      - minio_data:/bitnami/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: bucket
      MINIO_SCHEME: http
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  redis_dev:
  rabbitmq_data:
  minio_data:
