name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up mise
      uses: jdx/mise-action@v2
    - name: Install Python dependencies
      run: make install-py
    - name: Install frontend dependencies
      run: make install-js
    - name: Run lint
      run: make lint
    - name: Run tests
      run: make test
    - name: Build Docker image
      run: make docker-build
    # - name: Deploy
    #   run: make deploy